### ISSUE TITLE
Failed to install pdbfixer

### ISSUE THREAD

**Issue by albertma-evotec** [coleygroup/pyscreener#19]
Hi

git version: git version 2.31.GIT
pip version: pip 21.3.1 from /home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip (python 3.8)

I followed the README instruction to install pdbfixer, didnt work for some reason. problem of git?

```
(molpal) [ama@gpu04 Development]$ pip install git+https://github.com/openmm/pdbfixer.git
Collecting git+https://github.com/openmm/pdbfixer.git
  Cloning https://github.com/openmm/pdbfixer.git to /tmp/pip-req-build-hd4dk6vf
ERROR: Exception:
Traceback (most recent call last):
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 430, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 527, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 190, in unpack_url
    unpack_vcs_link(link, location)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 65, in unpack_vcs_link
    vcs_backend.unpack(location, url=hide_url(link.url))
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 598, in unpack
    self.obtain(location, url=url)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 512, in obtain
    self.fetch_new(dest, url, rev_options)
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 259, in fetch_new
    if self.get_git_version() >= (2, 17):
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 99, in get_git_version
    return tuple(int(c) for c in match.groups())
  File "/home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 99, in <genexpr>
    return tuple(int(c) for c in match.groups())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

Also tried git clone to local then install. Looks like some dependency issue??

```
(molpal) [ama@gpu04 Development]$ pip install -e pdbfixer
Obtaining file:///home/UK/ama/Development/pdbfixer
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/UK/ama/.conda/envs/molpal/lib/python3.8/site-packages (from pdbfixer==1.8.1) (1.21.2)
ERROR: Could not find a version that satisfies the requirement openmm>=7.1 (from pdbfixer) (from versions: 0.1, 0.2)
ERROR: No matching distribution found for openmm>=7.1
```

**Comment by davidegraff** [comment]
could you try uninstalling and reinstalling `openmm` then installing `pdbfixer`?

**Comment by davidegraff** [comment]
closing this due to inactivity
