### ISSUE TITLE
[JOSS review] Criptic error running example

### ISSUE THREAD

**Issue by rvhonorato** [coleygroup/pyscreener#22]
When running the provided example:
```python
# example/benzene_5wiu.py
import pyscreener as ps
import ray
ray.init()

metadata = ps.build_metadata("vina")
virtual_screen = ps.virtual_screen("vina", ["integration-tests/inputs/5WIU.pdb"], (-18.2, 14.4, -16.1), (15.4, 13.9, 14.5), metadata, ncpu=8)

scores = virtual_screen("c1ccccc1")
scores
```

```
$ python example/benzene_5wiu.py 
2022-01-12 14:20:06,884 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "example/benzene_5wiu.py", line 9, in <module>
    scores = virtual_screen("c1ccccc1")
  File "/Users/rodrigo/repos/pyscreener/pyscreener/docking/screen.py", line 169, in __call__
    planned_simulationsss = self.plan(sources, smiles)
  File "/Users/rodrigo/repos/pyscreener/pyscreener/docking/screen.py", line 243, in plan
    planned_simulationsss = [
  File "/Users/rodrigo/repos/pyscreener/pyscreener/docking/screen.py", line 244, in <listcomp>
    [
  File "/Users/rodrigo/repos/pyscreener/pyscreener/docking/screen.py", line 245, in <listcomp>
    [
  File "/Users/rodrigo/repos/pyscreener/pyscreener/docking/screen.py", line 246, in <listcomp>
    replace(
  File "/Users/rodrigo/software/anaconda3/envs/pyscreener_env/lib/python3.8/dataclasses.py", line 1264, in replace
    raise TypeError("replace() should be called on dataclass instances")
TypeError: replace() should be called on dataclass instances
(prepare_receptors pid=47498) Traceback (most recent call last):
(prepare_receptors pid=47498)   File "/Users/rodrigo/ADFRsuite-1.0/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 9, in <module>
(prepare_receptors pid=47498)     from MolKit import Read
(prepare_receptors pid=47498) ImportError: No module named MolKit
(prepare_receptors pid=47498) 
(prepare_receptors pid=47498) ERROR: failed to convert "integration-tests/inputs/5WIU.pdb"
```

**Comment by rvhonorato** [comment]
Actually just as I posted this I realized it is because there was something wrong with my `ADFRsuite-1.0` suite. Also it seems that `pyscreener` depends on this `prepare_receptor`, which is still python2, very unfortunate... 

I see that ADFR is also available as a conda package: https://anaconda.org/hcc/adfr-suite, is this a viable substitute?

**Comment by davidegraff** [comment]
It is unfortunate that `prepare_receptor` is still in python2. Even more unfortunate is that `openbabel` functions to prepare receptor result in _different_ files than `prepare_receptor`, so it doesn't seem like there's a python3 method by which to do this. Though I guess, there's no native python3 support for any of these docking programs, which is the whole thing we're trying to address here (basically hiding all the ugly parts of integrating docking into your own python workflow)

**Comment by davidegraff** [comment]
re: conda ADFR- I haven't tried with that package. The only requirement for it to work is that `prepare_receptor` is accessible on your path and produces the same results as the `prepare_receptor` when installing from source. Though I suspect that latter point is not much concern here...

**Comment by aviRevela** [comment]
I was wondering if there was a solution to this issue? I think my following error might also be a consequence that prepare_receptor is reliant on python2

`>>> import pyscreener as ps
>>> metadata = ps.build_metadata("vina")
>>> virtual_screen = ps.virtual_screen("vina", ["integration-tests/inputs/5WIU.pdb"], (-18.2, 14.4, -16.1), (15.4, 13.9, 14.5), metadata, ncpu=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/codebase/pyscreener/pyscreener/docking/__init__.py", line 88, in virtual_screen
    return DockingVirtualScreen(get_runner(software), *args, **kwargs)
  File "/home/jupyter/codebase/pyscreener/pyscreener/docking/screen.py", line 110, in __init__
    self.simulation_templates = self.prepare_receptors()
  File "/home/jupyter/codebase/pyscreener/pyscreener/utils/utils.py", line 119, in wrapper_run_on_all_nodes
    return ray.get(refs[-1])
  File "/opt/conda/envs/pyscreener/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/pyscreener/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ReceptorPreparationError): ray::prepare_receptors() (pid=8288, ip=10.142.0.15)
  File "/opt/conda/envs/pyscreener/lib/python3.8/subprocess.py", line 448, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['prepare_receptor', '-r', 'integration-tests/inputs/5WIU.pdb', '-o', PosixPath('/tmp/pyscreener/session_2022-06-08_21-20-08/inputs/5WIU.pdbqt')]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

ray::prepare_receptors() (pid=8288, ip=10.142.0.15)
  File "/home/jupyter/codebase/pyscreener/pyscreener/docking/screen.py", line 215, in prepare_receptors
    return [self.runner.prepare_receptor(template) for template in self.simulation_templates]
  File "/home/jupyter/codebase/pyscreener/pyscreener/docking/screen.py", line 215, in <listcomp>
    return [self.runner.prepare_receptor(template) for template in self.simulation_templates]
  File "/home/jupyter/codebase/pyscreener/pyscreener/docking/vina/runner.py", line 64, in prepare_receptor
    raise ReceptorPreparationError(
pyscreener.exceptions.ReceptorPreparationError: failed to prepare "integration-tests/inputs/5WIU.pdb". Message: Traceback (most recent call last):
  File "/home/jupyter/codebase/docking_software/ADFRsuite_x86_64Linux_1.0/ADFRSUITE/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 10, in <module>
    import MolKit.molecule
  File "/home/jupyter/codebase/docking_software/ADFRsuite_x86_64Linux_1.0/ADFRSUITE/CCSBpckgs/MolKit/molecule.py", line 23, in <module>
    from mglutil.util import misc
  File "/home/jupyter/codebase/docking_software/ADFRsuite_x86_64Linux_1.0/ADFRSUITE/CCSBpckgs/mglutil/util/misc.py", line 34, in <module>
    import numpy
  File "/home/jupyter/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/jupyter/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/jupyter/codebase/docking_software/ADFRsuite_x86_64Linux_1.0/ADFRSUITE/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /home/jupyter/.local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so: undefined symbol: PyUnicodeUCS4_FromObject
>>> exit`
