### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by yangziyi1990** [coleygroup/pyscreener#29]
After install pyscreener, I tried `pyscreener-check SCREEN_TYPE METADATA_TEMPLATE` command but encountered the following problems:

`Traceback (most recent call last):
  File "/data/yangziyi/anaconda3/envs/Relation/bin/pyscreener-check", line 8, in <module>
    sys.exit(check())
  File "/data/yangziyi/anaconda3/envs/Relation/lib/python3.8/site-packages/pyscreener/main.py", line 13, in check
    ps.check_env(sys.argv[1], json.loads(sys.argv[2]))
  File "/data/yangziyi/anaconda3/envs/Relation/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/yangziyi/anaconda3/envs/Relation/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/yangziyi/anaconda3/envs/Relation/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by davidegraff** [comment]
You’ve likely formatted your the string of the JSON struct incorrectly. Try running the software as intended with the `—smoke-test` flag added instead of using the pyscreener-check program

**Comment by yangziyi1990** [comment]
According to the Readme.md file, the `pyscreener` -- config path/to/your/config -- smoke-test` command line can check if everything is working and installed properly. What is the config file? Error when using integration-tests/configs/ as configuration path?

**Comment by yangziyi1990** [comment]
![1642745550115](https://user-images.githubusercontent.com/20346636/150475732-c2093452-f5a2-4c56-8ef3-fe9d1a8a38f6.jpg)

**Comment by davidegraff** [comment]
closing this due to inactivity
