### ISSUE TITLE
Question about running error

### ISSUE THREAD

**Issue by rebirthjin** [coleygroup/pyscreener#8]
Dear Authors,

I installed pyscreener in conda env. 

When I run the command "python run.py --config test_configs/test_vina.ini",
I got the error message like:

ERROR: failed to convert "testing_inputs/5WIU.pdb"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/njgoo/Data1/program/pyscreener/pyscreener/docking/__init__.py", line 8, in screener
    return Vina(software=software, **kwargs)
  File "/home/njgoo/Data1/program/pyscreener/pyscreener/docking/vina.py", line 102, in __init__
    super().__init__(receptors=receptors, pdbids=pdbids,
  File "/home/njgoo/Data1/program/pyscreener/pyscreener/docking/base.py", line 102, in __init__
    self.receptors = receptors
  File "/home/njgoo/Data1/program/pyscreener/pyscreener/docking/base.py", line 203, in receptors
    raise RuntimeError('Preparation failed for all receptors!')
RuntimeError: Preparation failed for all receptors!

Could you provide information for solving the error?
I also added external software path to PATH in bach_profile.

Thank you!

**Comment by davidegraff** [comment]
can you provide more information on what the contents of the file were and what your $PATH configuration is?

**Comment by rebirthjin** [comment]
The test_vina.ini file was distributed in github. The contents like this:

**name = test_vina

mode = docking
software = vina
receptors = [testing_inputs/5WIU.pdb]
ligands = [testing_inputs/test_ligands.csv]

center = [-18, 13.5, -17]
size = [14, 12, 15]** 

I only changed qvina into vina for docking software. 

Also, External software added in ~/.bah_profile.

export PATH=$PATH:~/ADFRsuite-1.0/bin
export PATH=$PATH:~/autodock_vina_1_1_2_linux_x86/bin

Thank you for response!
